export const payloadFieldsConfig = {
  title: "Payload Indexes",
  description: "We need to create indexes, if we want to do filtered search.",
  elements: [
    {
      type: "repeatable",
      name: "payload_fields",
      maxRepetitions: 10,
      elements: [
        {
          type: "string-input",
          title: "Field name",
          name: "field_name",
          placeholder: "Example: document-id",
          size: 12,
          required: true,
        },
        {
          type: "button-group-with-inputs",
          title: "Field type",
          name: "field_config",
          required: true,
          size: 12,
          enums: [
            { name: "keyword" },
            {
              name: "integer",
              fields: [
                {
                  title: "Allow match filters",
                  name: "lookup",
                  type: "checkbox",
                  default: true,
                  size: 3,
                },
                {
                  type: "description",
                  description: "This checkbox enables indexing of the integer field for exact match filters. \n If enabled, index will consume additional memory.",
                  link: "https://qdrant.tech/documentation/concepts/indexing/#parameterized-index",
                  linkText: "Learn more",
                  name: "lookup_description",
                  size: 9,
                },
                {
                  title: "Allow range filters",
                  name: "range",
                  type: "checkbox",
                  default: true,
                  size: 3,
                },
                {
                  type: "description",
                  description: "This checkbox enables indexing of the integer field for range filters. \n If enabled, index will consume additional memory.",
                  link: "https://qdrant.tech/documentation/concepts/indexing/#parameterized-index",
                  linkText: "Learn more",
                  name: "range_description",
                  size: 9,
                },
              ],
            },
            { name: "float" },
            { name: "uuid" },
            { name: "datetime" },
            {
              name: "text",
              fields: [
                {
                  title: "Tokenizer",
                  name: "tokenizer",
                  type: "dropdown",
                  options: ["prefix", "whitespace", "word", "multilingual"],
                  default: "whitespace",
                  size: 4,
                },
                {
                  type: "description",
                  description: "Defines how the text is tokenized",
                  link: "https://qdrant.tech/documentation/concepts/indexing/#full-text-index",
                  linkText: "Learn more",
                  name: "tokenizer_description",
                  size: 8,
                },
                {
                  title: "Lowercase",
                  name: "lowercase",
                  type: "checkbox",
                  default: true,
                  size: 4,
                },
                {
                  type: "description",
                  description: "Converts all characters to lowercase",
                  link: "https://qdrant.tech/documentation/concepts/indexing/#full-text-index",
                  linkText: "Learn more",
                  name: "lowercase_description",
                  size: 8,
                },
                {
                  title: "Min token length",
                  name: "min_token_len",
                  type: "number",
                  min: 1,
                },
                {
                  title: "Max token length",
                  name: "max_token_len",
                  type: "number",
                  min: 1,
                },
              ],
            },
            { name: "geo" },
            { name: "bool" },
          ],
        },
      ],
    },
  ],
};
